### ISSUE TITLE
Update for 8.0 ?

### ISSUE THREAD

**Issue by Raph67110** [kelvin-codes-stuff/Prestashop_discord_notify_module#6]
Hello,
Firstly I would like to thank you for your amazing work !
It's a great tool I would  use.

I have the Prestashop version 8.0.2, when I want to install this module, it says that the module is not compatible with my version.

are you considering an update? Or can I do something on my end ?

Have a good day

**Comment by Raph67110** [comment]
DiscordNotifyer.php line 16 : 
`		$this->ps_versions_compliancy = array("min" => "1.6", "max" => "8.99.99");
`
Seems to do the trick

**Comment by HeapReaper** [comment]
Hi @Raph67110, first of all i appreciate your reaction! I'm happy you like it.

I see you have the solution for now. I will update this repo for the new PS versions!

Greets, KelvinCodes
